name: movie
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  rxdart: ^0.27.7
  cached_network_image: ^3.2.1
  http: ^0.13.5
  flutter_launcher_icons: ^0.11.0
  get: ^4.6.5


  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/muvi_appicon.png"
flutter:

  uses-material-design: true

  assets:
    - assets/